### ISSUE TITLE
win dev ok?

### ISSUE THREAD

**Issue by nanmuyao** [ploggingdev/djangochat#1]
can win run this thans alot!

**Comment by ploggingdev** [comment]
The setup instructions will need to be changed for Windows.

Specifically :

```
sudo apt-get install python3-pip python3-dev libpq-dev postgresql postgresql-contrib
```

and the command to start the postgres prompt:

```
sudo -u postgres psql
```

and the location where the environment variables are specified:

```
sudo nano ~/.bashrc
```

You don't need to modify the Python/Django code though.
